from setuptools import setup, find_packages


setup(
    name='Starlit',
    version='0.1dev',
    description='A lightweight, modular, and extensible content management system.',
    license='MIT',
    author='Musharraf Omer',
    author_email='ibnomer2011@hotmail.com',
    packages=find_packages(),
    platforms='any',
    include_package_data=True,
    zip_safe=False,
    install_requires=[
      'Flask==0.12.2',
      'Flask-Admin==1.5.0',
      'Flask-BabelEx==0.9.3',
      'Flask-Cors==3.0.3',
      'Flask-Login==0.4.1',
      'Flask-Mail==0.9.1',
      'flask-marshmallow==0.8.0',
      'Flask-Migrate==2.1.1',
      'Flask-Permissions==0.2.3',
      'Flask-Principal==0.4.0',
      'Flask-RESTful==0.3.6',
      'Flask-Security==3.0.0',
      'Flask-SQLAlchemy==2.3.2',
      'Flask-WTF==0.14.2',
      'inflect==0.2.5',
      'marshmallow==2.15.0',
      'marshmallow-sqlalchemy==0.13.2',
      'Pillow==5.0.0',
      'six==1.11.0',
      'speaklater==1.3',
      'SQLAlchemy-Utils==0.32.21',
      'unicode-slugify==0.1.3',
      'WTForms-Components==0.10.3',
    ],
    classifiers=[
        'Development Status :: 4 - Beta',
        'Environment :: Web Environment',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
        'Topic :: Software Development :: Libraries :: Python Modules'
    ]
)